print("Reglas del juego UNO:")
print("1. Cada jugador comienza con 7 cartas.")
print("2. El resto de las cartas forma una pila boca abajo.")
print("3. Se voltea la primera carta de la pila para iniciar la pila de descarte.")
print("4. En su turno, cada jugador debe jugar una carta que coincida con el color o el número de la carta en la pila de descarte.")
print("5. Si un jugador no puede jugar, debe tomar una carta del mazo.")
print("6. Hay cartas especiales como +2, +4, cambio de color, reversa y salto.")
print("7. Si un jugador tiene solo una carta, debe gritar 'UNO'.")
print("8. Si otro jugador lo nota antes de que lo diga, debe robar 2 cartas.")
print("9. El primer jugador en quedarse sin cartas gana la ronda.")
print("10. Se puede jugar por rondas o con sistema de puntos acumulados.")